version: "3.7"

services:
  account_db:
    build:
      context: ./account
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: sunil
      POSTGRES_USER: sunil
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped
    ports:
      - "5432:5432"

  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
    restart: unless-stopped
    ports:
      - "9200:9200"

  order_db:
    build:
      context: ./order
      dockerfile: ./db.dockerfile
    environment:
      POSTGRES_DB: sunil
      POSTGRES_USER: sunil
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped
    ports:
      - "5433:5432"

  account:
    build:
      context: .
      dockerfile: ./account/app.dockerfile
    depends_on:
      - account_db
    environment:
      DATABASE_URL: postgres://sunil:123456@account_db/sunil?sslmode=disable
    restart: on-failure
    ports:
      - "8081:8080"

  catalog:
    build:
      context: .
      dockerfile: ./catalog/app.dockerfile
    depends_on:
      - catalog_db
    environment:
      DATABASE_URL: http://catalog_db:9200
    restart: on-failure
    ports:
      - "8082:8080"

  order:
    build:
      context: .
      dockerfile: ./order/app.dockerfile
    depends_on:
      - order_db
      - account
      - catalog
    environment:
      DATABASE_URL: postgres://sunil:123456@order_db/sunil?sslmode=disable
      ACCOUNT_SERVICE_URL: http://account:8080
      CATALOG_SERVICE_URL: http://catalog:8080
    restart: on-failure
    ports:
      - "8083:8080"

  graphql:
    build:
      context: .
      dockerfile: ./graphql/app.dockerfile
    depends_on:
      - account
      - catalog
      - order
    environment:
      ACCOUNT_SERVICE_URL: http://account:8080
      CATALOG_SERVICE_URL: http://catalog:8080
      ORDER_SERVICE_URL: http://order:8080
    restart: on-failure
    ports:
      - "8000:8080"
